# helm/todo-app/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if (hasKey .Values "workloadIdentityServiceAccount") }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentityServiceAccount }}
  {{- end }}
