# helm/postgres/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.postgres_creds }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.config.postgres_creds) }}
stringData:
{{ if $secret }}
  postgres-password: {{ index $secret.data "postgres-password" | b64dec  }}
  app-user-password: {{ index $secret.data "app-user-password" | b64dec  }}
  migrator-password: {{ index $secret.data "migrator-password" | b64dec  }}
  replication-password: {{ index $secret.data "replication-password" | b64dec  }}
{{ else }}
  postgres-password: {{ .Values.passwords.superuser | default (randAlphaNum 16) | quote }}
  app-user-password: {{ .Values.passwords.app | default (randAlphaNum 16) | quote }}
  migrator-password: {{ .Values.passwords.migrator | default (randAlphaNum 16) | quote }}
  replication-password: {{ .Values.passwords.replicator | default (randAlphaNum 16) | quote }}
{{ end }}
