# helm/postgres/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.postgres_creds }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.passwords.superuser | default (randAlphaNum 16) | quote }}
  app-user-password: {{ .Values.passwords.app | default (randAlphaNum 16) | quote }}
  migrator-password: {{ .Values.passwords.migrator | default (randAlphaNum 16) | quote }}
  replication-password: {{ .Values.passwords.replicator | default (randAlphaNum 16) | quote }}
  