# .github/actions/build-and-push/action.yaml
name: 'Build and Push Docker Images'
description: 'Builds todo-app Docker images and optionally pushes them to GCP Artifact Registry'

inputs:
  push_images:
    description: 'Whether to push images after building'
    required: true
  gcp_project_id:
    description: 'GCP Project ID'
    required: true
  gcp_region:
    description: 'GCP Region'
    required: true
    default: 'europe-west1'
  registry:
    description: 'Artifact Registry repository name'
    required: true
  image_tag:
    description: 'Tag to use for the images'
    required: true
  workload_identity_provider:
    description: 'Workload Identity Provider'
    required: true
  service_account:
    description: 'GCP Service Account email'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      id: gcp-auth
      if: inputs.push_images == 'true'
      uses: google-github-actions/setup-gcloud@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Login to GCP registry
      if: inputs.push_images == 'true'
      id: login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.gcp_region }}-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.gcp-auth.outputs.access_token }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push App Image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: src/Dockerfile
        push: ${{ inputs.push_images == 'true' }}
        tags: ${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.registry }}/todo-app:${{ inputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and Push Migrations Image  
      uses: docker/build-push-action@v6
      with:
        context: .
        file: migrations/Dockerfile
        push: ${{ inputs.push_images == 'true' }}
        tags: ${{ inputs.gcp_region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.registry }}/todo-app-migrations:${{ inputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
