# helm/migrations/values.yaml
namespace: todo_app
tolerations_workload_name: application

config:
  db_config: db-config 
  postgres_creds: postgres-creds

context: stage
image:
  repository: todo-app-migrations
  tag: latest
  pullPolicy: Never
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
