# helm/postgres/values.yaml
namespace: todo_app
tolerations_workload_name: database

# Core configurations that change between environments or are reused
image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

# Database configuration used across components
database:
  name: todos
  schema: todo_app

# Users referenced in multiple places
users:
  superuser: postgres
  app: todo_app_user
  migrator: todo_app_migrator
  replicator: replicator

# TODO: consider refactoring to get rid of these
passwords:
  superuser:
  app:
  migrator:
  replicator:

config:
  db_config: db-config
  postgres_creds: postgres-creds

# Resource configurations that vary per environment
primary:
  name: postgres-primary
  config_name: postgres-primary-config
  port: "5432"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    size: 1Gi

replica:
  name: postgres-replica
  config_name: postgres-replica-config
  port: "5432"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    size: 1Gi
