# helm/todo-app/values-gcp.yaml
ingress:
  gcp: true
  ipName: "${IP_NAME}"
  cert: todo-app-cert
  host: "${IP_ADDRESS}.nip.io"


workloadIdentityServiceAccount: "${GCP_SA_EMAIL}"

image:
  repository: ${IMAGE_REPOSITORY}/todo-app
  tag: ${TAG}
  pullPolicy: IfNotPresent
