# # .github/workflows/deploy.yaml
# name: Deploy

# on:
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Tag to deploy'
#         required: true
#         type: string

# env:
#   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   GKE_CLUSTER: sre-challenge-cluster-s
#   GKE_ZONE: europe-west1

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           ref: ${{ github.event.inputs.tag }}
      
#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ env.PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
          
#       - name: Get GKE credentials
#         uses: google-github-actions/get-gke-credentials@v1
#         with:
#           cluster_name: ${{ env.GKE_CLUSTER }}
#           location: ${{ env.GKE_ZONE }}
          
#       - name: Deploy to GKE
#         run: |
#           ./scripts/deploy_gcp.sh
#         env:
#           APP_IMAGE_TAG: ${{ github.event.inputs.tag }}